export type observation = {
  quality_grade: string,
  //time_observed_at: ,
  //taxon_geoprivacy: null,
  //annotations: [Array],
  //uuid: '1844a611-7e07-485e-906b-a8fc891101d4',
  //observed_on_details: [Object],
  id: number,
  cached_votes_total: number,
  identifications_most_agree: Boolean,
  //created_at_details: [Object],
  species_guess: string,
  identifications_most_disagree: Boolean,
  tags: [],
  positional_accuracy: number,
  comments_count: number,
  site_id: number,
  created_time_zone: string,
  //license_code: null,
  observed_time_zone: string,
  quality_metrics: [],
  public_positional_accuracy: number,
  //reviewed_by: [Array],
  //oauth_application_id: null,
  //flags: [],
  //created_at: '2024-12-04T18:54:49+01:00',
  //description: null,
 // time_zone_offset: '+01:00',
  //project_ids_with_curator_id: [],
  observed_on: string,
  observed_on_string: string,
  //updated_at: '2024-12-04T19:06:02+01:00',
  //sounds: [],
  place_ids: string[],
  captive: Boolean,
  taxon: [Object],
  //ident_taxon_ids: [Array],
  outlinks: [],
  faves_count: number,
  ofvs: [],
  num_identification_agreements: number,
  preferences: [Object],
  comments: [],
  //map_scale: null,
  uri: string,
  project_ids: [],
  //community_taxon_id: null,
  //geojson: [Object],
 // owners_identification_from_vision: true,
  //identifications_count: 0,
  obscured: Boolean,
  num_identification_disagreements: number,
  //geoprivacy: null,
  location: string, // lat,long
  votes: [],
  spam: Boolean,
  //user: [Object],
  mappable: Boolean,
  identifications_some_agree: Boolean,
  project_ids_without_curator_id: [],
  place_guess: string,
 // identifications: [Array],
  project_observations: [],
  observation_photos: [],
  photos: [],
  faves: [],
  non_owner_ids: []
}